route:
  group_by: ['node']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 10m
  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1265613414634356839/tBC7R5dnB4pzCXy8gTsY2v3dLSmHCpB0k1SHRGvtPDlaLEcwFG6s_KOfCWR3IE2A7Pw4
