services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yml:/etc/prometheus/rules.yml"
    ports:
      - 9090:9090
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8005:8080"
    deploy:
      mode: global
  alertmanager:
    image: prom/alertmanager
    volumes:
      - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    ports:
      - 9093:9093
