global:
  scrape_interval: 1m
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: node
    static_configs:
      - targets: ['172.20.107.60:8005']
        labels:
          node: 'sc4'
      - targets: ['172.20.107.61:8005']
        labels:
          node: 'sc5'
      - targets: ['172.20.107.62:8005']
        labels:
          node: 'sc6'
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
rule_files:
  - rules.yml
