groups:
- name: cadvisor
  rules:
  # Alert for any instance that is unreachable for >2 minutes.
  - alert: service_down
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "cAdvisor instance down"
      description: "The cAdvisor instance on {{ $labels.instance }} is down for more than 1 minute."
  - alert: high_load
    expr: node_load1 > 0.5
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."
